name: Boosted Balanced GARP Bi-Monthly Alert

on:
  schedule:
    - cron: '0 4 * * 1'  # Every Monday at 4AM UTC = 12PM SGT
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest
    env:
      PORTFOLIO_NAME:      ${{ secrets.PORTFOLIO_NAME }}
      SENDGRID_API_KEY:    ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_FROM:       ${{ secrets.SENDGRID_FROM }}
      SENDGRID_TO:         ${{ secrets.SENDGRID_TO }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python alert.py

