#name: Daily Boosted Balanced GARP Alert
#
#on:
#  schedule:
#    - cron: '0 4 * * *'  # 12PM SGT = 4AM UTC
#  workflow_dispatch:
#
#jobs:
#  alert:
#    runs-on: ubuntu-latest
#    env:
#      PORTFOLIO_NAME:      ${{ secrets.PORTFOLIO_NAME }}
#      SENDGRID_API_KEY:    ${{ secrets.SENDGRID_API_KEY }}
#      SENDGRID_FROM:       ${{ secrets.SENDGRID_FROM }}
#      SENDGRID_TO:         ${{ secrets.SENDGRID_TO }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'
#      - run: pip install -r requirements.txt
#      - run: python alert.py




name: Boosted Balanced GARP Bi-Monthly Alert

on:
  schedule:
    - cron: '0 4 * * 1'  # Every Monday at 4AM UTC = 12PM SGT
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest
    env:
      PORTFOLIO_NAME:      ${{ secrets.PORTFOLIO_NAME }}
      SENDGRID_API_KEY:    ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_FROM:       ${{ secrets.SENDGRID_FROM }}
      SENDGRID_TO:         ${{ secrets.SENDGRID_TO }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Check if it's 2nd or 4th Monday
        run: |
          python -c "
import datetime
today = datetime.datetime.utcnow() + datetime.timedelta(hours=8)  # SGT
monday_count = sum(1 for i in range(1, today.day + 1)
                   if datetime.date(today.year, today.month, i).weekday() == 0)
if monday_count not in [2, 4]:
    print(f'Skipping: Today is {monday_count}th Monday')
    exit(0)
"
      - run: python alert.py

